### ISSUE TITLE
Howest Boardgames followup

### ISSUE THREAD

**Issue by Zorth** [TarragonVZW/Dragons#36]
Check in with Katelijne with the necessary info.

**Comment by Zorth** [comment]
![Image](https://github.com/TarragonVZW/tarragonvzw.github.io/assets/16945970/a9134373-ad84-4f4f-9b47-c1b952dfc08c)

**Comment by Zorth** [comment]
- @PhaedraLambrecht & @SilverLionfang look into writing the infotext & promotext
- @SilverLionfang mail abt questions materiaal/sponsoring

**Comment by PhaedraLambrecht** [comment]
No awnser from Howest yet

**Comment by Zorth** [comment]
still waiting on followup

**Comment by Zorth** [comment]
Discord and website has been brought in order
