### ISSUE TITLE
Pendragon Wizarding Quiz

### ISSUE THREAD

**Issue by Zorth** [TarragonVZW/Dragons#47]
Live date: 25/02/2024

**Comment by PhaedraLambrecht** [comment]
**1. In Mario Kart, the power-up that seeks out the player in first position and explodes on impact. what collor is this power-up?**
Hint: it is a shell.
awnser: blue.


**2. What video game for the NES was released in the late 1980s, and was meant to be played with the NES Zapper gun?**
Hint: it shares a cartridge with "super mario bros".
Awnser: Duck Hunt.


**3. Name as many of the first 6 games that were included into the World Video Game Hall of Fame.**
Awnser: Pong, Tetris, Pac-Man, Super Mario Bros, DOOM, World of Warcraft.


**4. What card game did Blizzard release in 2014?**
Hint: it is related to "Warcraft".
Awnser: Heartstone.


**5. What regulatory group assigns content rating and suggested age ratings for video games?**
Hint: the acronym is ESRB.
Awnser: Entertainment Software Rating Board.


**6. Sun, Moon, Diamond, Pearl, and SoulSilver have all been names of games in what iconic video game franchise?**
Awnser: Pokemon.


**7. Chuck E. Chees was originally founded by Nolan Bushnell who also co-founded what video game company?**
Hint: it is well known for its 2600.
Hint2: helped define the electronic entertainment industry.
Awnser: Atari.


**8. What pokemon holds the title as the first listed creature in the pokedex?**
Hint: considered a hybrid grass-poison type.
Awnser: Bulbasaur.


**9. What video game has an owl named Blathers?**
Hint: It is a game created by Nintendo.
Awnser: Annimal crossing.


**10. Complete the next line: ".... does what NintenDon't."**
Awnser: Genesis.


**11. Desmond Miles is a fictional character and the main protagonist of the first few installments in what series of videogames?**
Hint: Ubisoft's best selling franchise.
Awnser: Assasin's Creed.


**12. What was Mario's original proffesion?**
Hint: it is not Plumber.
Awnser: Carpenter.


**13. What is the original name of the creater of minecraft?**
Hint: his nickname is Notch.
awnser: Markus Persson.


**14. What company is behind the experimental project in "Assasin's Creed"?**
Awnser: Astbergo.


**15. In what console can you play "Crissis Core: Final Fantasy"?**
Hint: It is a handheld
Awnser: PSP


**16. What was the first game played in space?**
Hint: It is an old arcade game.
Awnser: Tetris.


**17. Who is Sonic's sidekick?**
Hint: nickname is Tails (if this is not needed then Tails is a good awnser).
Awnser: Miles Prower.


**18. what is the fictional language used in video games called?**
Hint: the acronym is SGA.
Hint2: it is seen in the mincraft enchanting table language.
Awnser: Standard Galactic Alphabet.


**19. What is the name of the sequel to "Half-life"?**
Hint: you don't need a hint trust me.
Awnser: Half-life 2.


**20. What is the name of the team behind the development of "Among Us"?**
Hint: it has an animal in the name
Awnser: InnerSloth

**Comment by Bork114** [comment]
**1. In what county did the 1896 Olympic Games take place?**
Hint: The 1896 Olympics marked the start of the modern Olympics.
Answer: Greece

**2. In what order do Triathlon sports take place?**
Hint: One is 1.5 km long, the next is 40 km long and the last leg takes 10 km.
Answer: Swim, Bike and run

**3. Who holds the record of most Olympian medals won?**
Hint: His performance in the Rio Olympics was unique in _"winning multiple gold medals at 31 years old, well beyond the typical peak for male swimmers"_
Answer: Michael Phelps

**4. In what country is the biggest tennis tournament "Wimbledon" taking place?**
Hint: It's in a land with lots of rain.
Answer: England

**5. Who won the 10th Italian Open title in 2021?**
Hint: Ironically, he is Spanish.
Answer: Rafael Nadal.

**6. What is the name of the most renown boxer of all time?**
Hint: He passed way in June 2016.
Answer: Muhammad Ali

**7. Which sport takes place in a velodrome?**
Hint: It's in the name.
Answer: Cycling

**8. In darts what is the highest score from a single dart?**
Hint: It's a triple of the highest number or the bord.
Answer: 180.

**9. What martial sport has tried to be part of the Olympics since 1970's?** 
Hint: If you don't do Judo, you do this instead.
Answer: Karate

**10. What country only holds two World Cups?**
Hint: They won one in 1998 and another in 2018
Answer: France

**11. Which Belgian woman racing cyclist has currently won 6 gold medals?**
Hint: Her most recent win was the Road Race on the World Championships in August 2023.
Answer: Lotte Kopecky

**12. Only three countries have won the Women's Rugby World Cup. New Zealand, England and?**
Hint: Rugby is a favourite sport there.
Answer: USA

**13. Which footballer holds the world record for the highest goal scorer for a single club?**
Hint: He used to play for Barcelona
Awnser: Lionel Messi

**Comment by GrimmSlayingDolt** [comment]
Board game trivia 

1. What classic board game does the phrase "Back to square one" originate from? (Can be answered in Dutch)
- Answer: “Snakes and Ladders", "Chutes and Ladders”, "Slangen en ladders" or "Ladderspel"

2. What constitutes being “busted” in the game Blackjack?
- Answer: A score of 22 or higher.

3. What game has pieces representing winds, dragons, flowers, and seasons?
- Hint 1: In ancient China to predict future events.
- Hint 2: In this game, it is important to match identical pairs of tiles.
- Answer: "Mahjong" or "Mah-jongg"

4. What classic board game is a simplified version of Capture the Flag? 
- Answer: Stratego

5. In the current version of Battleship, your ships will cover how many squares in total?
- Answer: 17

6. Which card game has a variation known as “Exploding Kittens”?
- Hint 1: This is an old lethal Russian game
- Answer: Russian Roulette

7. What is the most expensive card ever sold in the history of Magic: The Gathering?
- Answer: Black Lotus (Alpha Set)

8. Which game was originally called Lexico, then Crisscross Words and later changed again?
- Answer: Scrabble

9. Chinese checkers was actually created in what country?
- Answer: Germany

10. Which classic board game involves solving a murder?
- Answer: Cluedo

11. Which one is NOT a type of the card game "Solitaire"? Free Cell | Klondike | Fish | Spider
- Answer: Fish

12. What game lets you be a dispatcher, medic, scientist, operations expert or researcher?
- Answer: Pandemic

13. How many chess pieces are on one side of chess?
- Answer: 16

14. In Monopoly, what words are written alongside the jail square?
- Answer: Just visiting

15. How many categories are there in the classic Trivial Pursuit game?
- Answer: 6

16. Which one of these is NOT a way to go to jail during a standard Monopoly game? Landing on the jail square by roll of the dice | Landing on the Go to Jail square by roll of the dice | Drawing a card marked "Go to Jail" | Throwing doubles three times in a row
- Answer: Landing on the jail square by roll of the dice

17. What are the four suits in a standard deck of playing cards? (Can be answered in Dutch)
- Answer: "Hearts, Diamonds, Clubs, and Spades"  or "Schoppen, Harten, Ruiten, Klaveren"

18. Which board game requires players to remove various body parts from a patient without touching the edges of the cavity? (can be answered in Dutch)
- Answer: "Operation" or "Dr. Bibber"

19. How many dice are used in a game of Yahtzee?
- Answer: 5

20. In Chess, what is the term used when a player has no legal moves left but their king is not in check? Check | Checkmate | Stalemate | Fool's Mate
- Answer: Stalemate

21. In the game of Ticket to Ride, what is the objective?
- Answer: To connect cities with train routes and score the most points.

22. In the game of Pandemic, how many diseases must players cure to win the game?
- Answer: 4

23. Which card game was originally a mod for the video game “Warcraft III”?
- Answer: Hearthstone

24. What board game was used by the French military as a training tool during the late 19th century?
- Answer: Risk

25. Which board game was created by a Canadian couple as a way to entertain their friends at parties?
- Answer: Trivial pursuit

26. What was the first board game to be played in space?
- Answer: Scrabble

27. What was the first collectible trading card game ever invented?
- Answer: Magic: The Gathering

28. In which country was the game of Chess invented?
- Answer: India

29. What board game was inspired by an actual real-life treasure hunt?
- Answer: Treasure hunt

30. What is the world record for the most players in a single game of Monopoly? 325 | 148 | 720 | 585
- Answer: 585

31. In which card game is there one card that no player wants. If you have this card at the end of the game, you lose? War | Spoons | Old Maid | Go Fish
- Answer: Old Maid

32. Which cube shaped game was invented by a Hungarian architect in 1974 and is considered one of the most challenging puzzles of all time?
- Answer: Rubik’s Cube

33. Who is the unfortunate victim in the game Clue?
- Answer: Mr. Boddy

34. How many female characters appear in the original Guess Who? 3 | 5 | 8 | 12
- Answer: 5

35. What is the largest number of players that can play Texas Hold’em poker at once?
- Answer: Ten

36. Including jokers, how many cards are in a standard deck?
- Answer: 54

37. What’s the highest hand possible in standard poker?
- Answer: A Royal Flush

38. What country were cardboard playing cards invented in?
- Answer: China

39. Statistically speaking, what are the two worst cards to be dealt in Texas Hold ‘Em?
- Answer: A Two and a Seven of different suits.

**Comment by Cistem35** [comment]
1. Abraham Lincoln presidency was the first to end early in what way? (murdered)
2. Despite never building one, who's theory helped the construction of the atomic bomb? (Einstein)
3. Between wich time period did the french revolution occur? (only need the years: 1789 - 1799)
4. What was the name of the role of the person who deciceded the fate of the losing gladiator in gladiator fights? (Editor)
5. During world war 2, Japan had pilots crash their plane with explosives into their enemies, what were those pilots called? (Kamikaze)
6. Who where the first europeans to land in america? (the vikings)
7. When did the Berlin wall fall? (november 9 1989)
8. What was Hitler's role in world war 1? (soldier in the front lines)
9. Who sailed around the world first? (Ferdinand Magellan)
10. Who was the second United states president? (Jhon Adams)

**Comment by Zorth** [comment]
1. Which world famous short film was released into the public domain as of 2024?
	- Steamboat Willie
2. What is the name for the Hindi cinema industry?
	- Bollywood
3. Which hit film starring Keanu Reeves, came out in 1999?
	- The Matrix
4. Who will be back?
	- Arnold Schwarzenegger (Terminator)
5. Which well known British Hollywood director has directed "Oppenheimer", "Interstellar", "Tenet", and "Inception"
	- Christopher Nolan
6. Who was the lead producer of Barbie (2023)?
	- Margot Robbie
7. Which film festival, previously called "The international film festival" untill 2002, is widely regarded as the most popular/famous?
	- Cannes
8. What width is the original film strip and now is often referred to as "Full frame"?
	- 35 mm
9. From which movie is "A tale as old as time"?
	- Beauty and the beast
10. Which Steven Spielberg movie featured a puppet of an extraterrestrial as one of the main characters?
	- E.T.
