### ISSUE TITLE
Cosplay Workshop

### ISSUE THREAD

**Issue by Zorth** [TarragonVZW/Dragons#49]
Live date: 07/04/2024
**Venturer:** @Bork114 
**Absent:**
- @Bork114 

**Photographer:** 

-

**Materials:**
The list is on the [google drive](https://docs.google.com/spreadsheets/d/1Tbzxioyti_-HrviebMIBuxekA20aPTmf/edit#gid=961235229_). Check the third tab on who bring what.

**Madolorian Workshop:**

-
-

**Valorant Workshop:**

-
-

**Workshop explanations**:  [Explantions](https://drive.google.com/drive/u/1/folders/1uC1w0AWChhepqMJgXAiDsjvcyiVcsurV)

**Crowed Control**

-
-

[**Google Form**](https://docs.google.com/forms/d/1qOGnLBsor8aIbth32VGEkmaao-M5eUviQ2UlmhZssFs/edit)

**Comment by Bork114** [comment]
**Venturer:** Mattis

**Attended:**

**Photographer:** 

**Materials:**

**Comment by Bork114** [comment]
- [x] Find Cardboard Cosplay, min two per person ( Deadline 24/03/2024)
- [x] Find material for the Cosplays

**Comment by GrimmSlayingDolt** [comment]
Cardboard cosplay ideas (all include free templates):

Easy:
1. My Hero Academia Bakugo's gauntlets: https://www.youtube.com/watch?v=q_OvWQyHAj4
2. Pokemon ball: https://www.youtube.com/watch?v=_zNp5eWdhzI (Tooth pick if opanable)
3. Wolf mask: https://www.youtube.com/watch?v=jPDnRp2Thko
4. Loki Helmet: https://www.youtube.com/watch?v=oyeSDn1vA2Q

Medium:
1. Chainsaw Man Helmet: https://www.youtube.com/watch?v=UeL52tnX7Vo (2 rubber bands needed each)
2. Valorant tactical knife: https://www.youtube.com/watch?v=miNyMxyLP_s
3. Robot helmet: https://www.instructables.com/DIY-Japanese-Robot-Cardboard-Helmet/

Advanced:
1. Stormtrooper helmet: https://dali-lomo.blogspot.com/2014/10/star-wars-stormtrooper-helmet-diy.html

**Comment by SebastianMaxG** [comment]
- https://www.instructables.com/Cardboard-Plague-Mask/

- https://www.instructables.com/Adventure-Time-Ice-Kings-Crown-Cosplay-Headpiece/

- https://www.instructables.com/Cardboard-Master-Sword/

**Comment by Cistem35** [comment]
https://youtu.be/bVUNPRVA08w

https://youtu.be/jU_fq_VRS0w

**Comment by SilverLionfang** [comment]
- https://tamasoft.co.jp/pepakura_designer/
- [Lion Mask.pdf](https://github.com/TarragonVZW/Dragons/files/14823349/Lion.Mask.pdf)
